language: go

go:
  - 1.6

before_install:
  - go get gopkg.in/check.v1
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo
  - go get golang.org/x/tools/cmd/cover

script:
  - bash test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)